config/routes.rb
Rails.application.routes.draw do
  get 'parties/index'
  devise_for :users
  root to: "parties#index"

  resources :parties, only: [:index, :show, :create] do
    member do
      patch :stop_partying
    end
  end

  resources :drugs, only: [:index] do
    resources :takes, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/drug.rb
class Drug < ApplicationRecord
  has_one :take, dependent: :destroy
end

app/models/party.rb
class Party < ApplicationRecord
  belongs_to :user
  has_many :takes, dependent: :destroy
end

app/models/take.rb
class Take < ApplicationRecord
  belongs_to :drug
  belongs_to :party
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :parties, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/drugs_controller.rb
class DrugsController < ApplicationController
  def index
    @party = Party.last
    @drugs = Drug.all
    @takes = Take.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  def index
    @parties = Party.all
  end

  def show
    @party = Party.find(params[:id])
  end

  def create
    Party.create!(user: current_user)
    redirect_to drugs_path
  end

  def stop_partying
    party = Party.find(params[:id])
    party.update(ending_time: Time.now)

    redirect_to parties_path
  end
end

app/controllers/takes_controller.rb
class TakesController < ApplicationController

  def new
    drug = Drug.new
    redirect_to :back

  end

  def create
    party = Party.last
    drug = Drug.find(params[:drug_id])
    Take.create!(drug: drug, party: party)

    redirect_to drugs_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drugs_helper.rb
module DrugsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/helpers/takes_helper.rb
module TakesHelper
end

app/views/drugs/index.html.erb
<h1>Happy Party</h1>
<p>Started on <%= @party.created_at.strftime('%d/%m/%Y - %H:%M') %></p>
<p>It's <%= Time.now.strftime('%H:%M') %> </p>
<% if @takes.count == 0 %>
  <p>You haven't take anything yet</p>
<% else %>
  <p>Last take: <%= @takes.last.drug.name %> at <%= @takes.last.created_at.strftime('%H:%M') %></p>
  <p>Total takes: @takes.count</p>
<% end %>

<%= link_to 'See details', party_path(@party) %>


<% @drugs.each do |drug| %>
  <%= render 'shared/drug_card', drug: drug %>
<% end %>


<%= link_to "Party's over, go to sleep", stop_partying_party_path(@party), method: :patch %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyConso</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Hi gurl</h1>

app/views/parties/index.html.erb
<h1>Welcome to you fucker</h1>

<%= link_to parties_path, method: :post do  %>
  <h2>Start Partying</h2>
<% end %>

<% @parties.each do |party| %>
  <%= render 'shared/party_card', party: party %>
<% end %>

app/views/parties/show.html.erb
<h1>Your party on <%= @party.created_at.strftime('%d/%m/%Y') %></h1>
<p>First take: <%= @party.takes.first.created_at.strftime('%d/%m/%Y - %H:%M') %></p>
<p>Last take: <%= @party.takes.last.created_at.strftime('%d/%m/%Y - %H:%M') %></p>
<p>Total takes: <%= @party.takes.count %> </p>
<% @party.takes.each do |take| %>
  <%= render 'shared/take_line', take: take %>
<% end %>

app/views/shared/_drug_card.html.erb
<%= link_to drug_takes_path(drug), method: :post  do %>
  <div>
    <h1><%= drug.name %></h1>
  </div>
<% end %>

app/views/shared/_party_card.html.erb
<%= link_to party_path(party) do  %>
  <div>
    <h2><%= party.created_at.strftime('%d/%m/%Y')%></h2>
    <p><%= party.takes.count %> takes</p>
  </div>
<% end %>

app/views/shared/_take_line.html.erb
<p><%= take.created_at.strftime('%H:%M') %> | <%= take.drug.name %></p>